name: BuildAndCommit

env:
  TZ: Asia/Shanghai

on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          rm -rf backend
          rm -rf frontend
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Waikkii
          author_email: 707647403@qq.com
          message: "GitHub Actions Auto Commit"
          add: "backend/static"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
