name: buildAndDeploy

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - main

# 开始任务
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Update dist folder to repository
        env:
          REPO_USERNAME: "Waikkii"
          DIST_REPO: "Waikiki_ninja"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          git config --global user.email "Action@GitHub.com"
          git config --global user.name "GitHub Action"
          cd dist && git init && git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://$GITHUB_TOKEN@github.com/$REPO_USERNAME/$DIST_REPO.git" master:master
